name: Test Coverage Check

on:
  push:
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.11"
          cache: "pip"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          make install-dev

      - name: Run tests with coverage
        env:
          PYTHONPATH: ${{ github.workspace }}/backend
        run: |
          make test
          make clean
