name: Test Coverage Check

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.11"
          cache: "pip"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          make install-dev

      - name: Run tests with coverage
        run: |
          cd backend
          PYTHONPATH=$PWD python -m pytest \
            --cov=core \
            --cov=main.py \
            --cov-report=term-missing \
            --cov-report=html \
            --cov-config=.coveragerc \
            tests/ \
            --cov-fail-under=100

      - name: Clean up
        if: always()
        run: make clean
